export const reducerCases = {
  IS_MORE_OPEN: "IS_MORE_OPEN",
  IS_CHAT_OPENED: "IS_CHAT_OPENED",
  IS_TYPE_SETTING: "IS_TYPE_SETTING",
  SET_USER_INFO: "SET_USER_INFO",
  SET_RELATION_INFO: "SET_RELATION_INFO",
  
};
